<a href="https://colab.research.google.com/github/Cyber-Nischal/WS_AI/blob/main/Workshop5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

def cost_function(X,Y,W):
  """ Parameters:
  This function finds the Mean Square Error.
  Input parameters:
   X: Feature Matrix
   Y: Target Matrix
   W: Weight Matrix
  Output Parameters:
   cost: accumulated mean square error.
  """
  y_pred = X.dot(W)
  e = (y_pred - Y) ** 2
  m = len(Y)
  cost = 1/(2*m)*np.sum(e);

  return cost
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])
cost = cost_function(X_test, Y_test, W_test)
print(cost)



0.0


In [ ]:
def gradient_descent(X, Y, W, alpha, iterations):
  """
  Perform gradient descent to optimize the parameters of a linear regression model.
  Parameters:
  X (numpy.ndarray): Feature matrix (m x n).
  Y (numpy.ndarray): Target vector (m x 1).
  W (numpy.ndarray): Initial guess for parameters (n x 1).
  alpha (float): Learning rate.
  iterations (int): Number of iterations for gradient descent.
  Returns:
   tuple: A tuple containing the final optimized parameters (W_update) and the history of cost values
       .
          W_update (numpy.ndarray): Updated parameters (n x 1).
          cost_history (list): History of cost values over iterations.
  """
  # Initialize cost history
  cost_history = [0] * iterations
  # Number of samples
  m = len(Y)
  for iteration in range(iterations):
    # Step 1: Hypothesis Values
    Y_pred = X.dot(W)
    # Step 2: Difference between Hypothesis and Actual Y
    loss = Y_pred - Y
    # Step 3: Gradient Calculation
    dw = (X.T.dot(loss))/m
    # Step 4: Updating Values of W using Gradient
    W_update = W - alpha * dw
    # Step 5: New Cost Value
    cost = cost_function(X,Y,W_update)
    cost_history[iteration] = cost
  return W_update, cost_history

# Generate random test data
np.random.seed(0) # For reproducibility
X = np.random.rand(100, 3) # 100 samples, 3 features
Y = np.random.rand(100)
W = np.random.rand(3) # Initial guess for parameters
# Set hyperparameters
alpha = 0.01
iterations = 1000
# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
# Print the final parameters and cost history
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

NameError: name 'cost_function' is not defined

Worksheet II

In [ ]:
import numpy as np

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)

z = np.array([[1,2,3],[1,2,3]])
print(softmax(z))



[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


In [ ]:
import numpy as np

def loss_softmax(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred + 1e-10))

y_true = np.array([0,0,1])
y_pred = np.array([0.1,0.2,0.7])
print(loss_softmax(y_true, y_pred))


0.3566749437958753


In [ ]:
import numpy as np

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)

def cost_softmax(X, y, W, b):
    z = np.dot(X, W) + b
    y_pred = softmax(z)
    return -np.sum(y * np.log(y_pred + 1e-10)) / X.shape[0]

X = np.array([[1,2],[2,3],[3,4]])
y = np.array([[1,0,0],[0,1,0],[0,0,1]])
W = np.zeros((2,3))
b = np.zeros(3)

print(cost_softmax(X, y, W, b))


1.0986122883681098


In [ ]:
import numpy as np

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)

def compute_gradient_softmax(X, y, W, b):
    n = X.shape[0]
    y_pred = softmax(np.dot(X, W) + b)
    grad_W = np.dot(X.T, (y_pred - y)) / n
    grad_b = np.sum(y_pred - y, axis=0) / n
    return grad_W, grad_b

X = np.array([[1,2],[2,3],[3,4]])
y = np.array([[1,0,0],[0,1,0],[0,0,1]])
W = np.zeros((2,3))
b = np.zeros(3)

print(compute_gradient_softmax(X, y, W, b))


(array([[ 3.33333333e-01, -9.25185854e-17, -3.33333333e-01],
       [ 3.33333333e-01, -7.40148683e-17, -3.33333333e-01]]), array([-3.70074342e-17, -3.70074342e-17, -3.70074342e-17]))


In [ ]:
import numpy as np

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)

def cost_softmax(X, y, W, b):
    z = np.dot(X, W) + b
    y_pred = softmax(z)
    return -np.sum(y * np.log(y_pred + 1e-10)) / X.shape[0]

def compute_gradient_softmax(X, y, W, b):
    n = X.shape[0]
    y_pred = softmax(np.dot(X, W) + b)
    return np.dot(X.T, (y_pred - y)) / n, np.sum(y_pred - y, axis=0) / n

def gradient_descent_softmax(X, y, W, b, alpha, n_iter):
    for _ in range(n_iter):
        gW, gb = compute_gradient_softmax(X, y, W, b)
        W -= alpha * gW
        b -= alpha * gb
    return W, b

X = np.array([[1,2],[2,3],[3,4]])
y = np.array([[1,0,0],[0,1,0],[0,0,1]])
W = np.zeros((2,3))
b = np.zeros(3)

W, b = gradient_descent_softmax(X, y, W, b, 0.1, 500)
print(W, b)


[[-2.40349375  0.13118344  2.27231031]
 [ 0.45363773  0.09304183 -0.54667956]] [ 2.85713148 -0.03814162 -2.81898986]


In [ ]:
import numpy as np

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)

def predict_softmax(X, W, b):
    return np.argmax(softmax(np.dot(X, W) + b), axis=1)

X = np.array([[1,2],[2,3],[3,4]])
W = np.array([[1,0,-1],[0,1,-1]])
b = np.zeros(3)

print(predict_softmax(X, W, b))


[1 1 1]


In [ ]:
import numpy as np

def evaluate_classification(y_true, y_pred):
    c = len(np.unique(y_true))
    cm = np.zeros((c,c), dtype=int)
    for t,p in zip(y_true,y_pred):
        cm[t,p] += 1
    precision = np.mean([cm[i,i]/np.sum(cm[:,i]) if np.sum(cm[:,i])>0 else 0 for i in range(c)])
    recall = np.mean([cm[i,i]/np.sum(cm[i,:]) if np.sum(cm[i,:])>0 else 0 for i in range(c)])
    f1 = 2*precision*recall/(precision+recall) if precision+recall>0 else 0
    return cm, precision, recall, f1

y_true = np.array([0,1,2])
y_pred = np.array([0,2,2])

print(evaluate_classification(y_true, y_pred))


(array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1]]), np.float64(0.5), np.float64(0.6666666666666666), np.float64(0.5714285714285715))
