<a href="https://colab.research.google.com/github/Cyber-Nischal/WS_AI/blob/main/WS_1_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEM 1
1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np

arr_empty = np.empty((2,2))
print(arr_empty)


[[5.22437812e-315 0.00000000e+000]
 [6.67743717e-310 6.67743717e-310]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

arr_ones = np.ones((4,2))
print(arr_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

arr_full = np.full((3,3), 7)
print(arr_full)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

given_array = np.array([[4, 8], [10, 12]])
zeros_array = np.zeros_like(given_array)
print(zeros_array)


[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

given_array = np.array([[4, 8], [10, 12]])
ones_array = np.ones_like(given_array)
print(ones_array)


[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)


[1 2 3 4]


PROBLEM 2
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

arr = np.arange(10, 50)
print(arr)


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3,3)
print(matrix)


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

arr = np.random.random((10,10))
print("Array:\n", arr)
print("Minimum value:", arr.min())
print("Maximum value:", arr.max())


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

arr = np.zeros(10)
arr[4] = 1  # 5th element has index 4
print(arr)


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print(reversed_arr)


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

checkerboard = np.indices((8,8)).sum(axis=0) % 2
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


PROBLEM-3


For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

result = x + y
print(result)


2. Subtract the two array.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

result = x - y
print(result)


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])

result = x * 3  # multiply each element by 3
print(result)


4. Find the square of each element of the array.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])

squared = x ** 2
print(squared)


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

dot_vw = np.dot(v, w)
print("v · w =", dot_vw)

dot_xv = np.dot(x, v)
print("x · v =", dot_xv)

dot_xy = np.dot(x, y)
print("x · y =\n", dot_xy)


v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

concat_xy_rows = np.vstack((x, y))
print("Concatenate x and y along rows:\n", concat_xy_rows)

concat_vw_cols = np.column_stack((v, w))
print("\nConcatenate v and w along columns:\n", concat_vw_cols)


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
v = np.array([9,10])

try:
    concat_xv = np.concatenate((x, v))
    print(concat_xv)
except Exception as e:
    print("Error:", e)


PROBLEM 4


• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])

A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

result_rounded = np.round(result)

print("A * A^-1 =\n", result_rounded)


2. Prove AB ̸= BA.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("A * B =\n", AB)
print("\nB * A =\n", BA)
print("\nCheck if AB equals BA:", np.array_equal(AB, BA))


3. Prove (AB)

T = BTAT

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Compute (AB)^T
AB_T = np.dot(A, B).T

# Compute B^T * A^T
B_TA_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("\nB^T * A^T =\n", B_TA_T)
print("\nCheck if (AB)^T equals B^T*A^T:", np.array_equal(AB_T, B_TA_T))


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

A_inv = np.linalg.inv(A)
X = A_inv.dot(B)

print(X)  # [x, y, z]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
], dtype=float)


B = np.array([-1, -3, 9], dtype=float)

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution using np.linalg.inv():")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])
